services:
  frontend:
    build:
      context: ../packages/frontend
      dockerfile: Dockerfile
    container_name: fs-frontend
    ports:
      - "3000:3000"
    volumes:
      - ../packages/frontend:/app
      - frontend-node-modules:/app/node_modules
    environment:
      - VITE_GRAPHQL_URL=http://localhost:4000/graphql
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - app-network
    command: yarn dev

  backend:
    build:
      context: ../packages/backend
      dockerfile: Dockerfile
    container_name: fs-backend
    ports:
      - "4000:4000"
    volumes:
      - ../packages/backend:/app
      - backend-node-modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/fs-technical-test
      - ENERGY_API_URL=https://apidatos.ree.es/es/datos/balance/balance-electrico
    depends_on:
      - mongo
    networks:
      - app-network
    command: yarn dev

  mongo:
    image: mongo:latest
    container_name: fs-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-data-test:/data/test-db
    environment:
      - MONGO_INITDB_DATABASE=fs-technical-test
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
  mongo-data-test:
  frontend-node-modules:
  backend-node-modules:
